q=input("Введите список слов: ")
a=set()
q=q.split()
a.update(q)
print("Кол-во слов: "+str(len(a)))
w=input("Введите список с таким же кол-вом слов: ")
b=set()
w=w.split()
b.update(w)
s=dict(zip(a,b))
print(s)
input()
